DROP TABLE SHOP;

CREATE TABLE SHOP (
  SHOP_NO DOUBLE NOT NULL,
  SHOP_NAME VARCHAR(100),
  SHOP_LOCATION LONGTEXT,
  SHOP_STATUS VARCHAR(20),
  CONSTRAINT SHOP_PK PRIMARY KEY (SHOP_NO)
);

INSERT INTO SHOP (SHOP_NO,SHOP_NAME,SHOP_LOCATION,SHOP_STATUS) VALUES (1,'Toy Store','A Tower Seocho dong','Y');
INSERT INTO SHOP (SHOP_NO,SHOP_NAME,SHOP_LOCATION,SHOP_STATUS) VALUES (2,'Play Store','B Tower Seocho dong','Y');
INSERT INTO SHOP (SHOP_NO,SHOP_NAME,SHOP_LOCATION,SHOP_STATUS) VALUES (3,'Mom Store','C Tower Seocho dong','Y');
COMMIT;


DROP TABLE TOY;


CREATE TABLE TOY (
  TOY_NO DOUBLE NOT NULL,
  TOY_NAME VARCHAR(100),
  TOY_PRICE DOUBLE,
  SHOP_NO DOUBLE NOT NULL,
  CONSTRAINT TOY_PK PRIMARY KEY (TOY_NO)
);


INSERT INTO TOY (TOY_NO,TOY_NAME,TOY_PRICE,SHOP_NO) VALUES (1,'Lego (Model-A100)', 30000, 1);
INSERT INTO TOY (TOY_NO,TOY_NAME,TOY_PRICE,SHOP_NO) VALUES (2,'Lego (Model-A200)', 60000, 1);
INSERT INTO TOY (TOY_NO,TOY_NAME,TOY_PRICE,SHOP_NO) VALUES (3,'Lego (Model-A300)', 90000, 1);
COMMIT;


# CALL DropSequence('SEQ_SHOP_NO');

# CALL CreateSequence('SEQ_SHOP_NO', 4, 1);